name: C++ CI and Benchmark

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Build Dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake

    - name: Configure CMake (Debug)
      run: cmake -B build-debug -DCMAKE_BUILD_TYPE=Debug -S .

    - name: Build Project (Debug)
      run: cmake --build build-debug

    - name: Run Unit Tests
      run: ./build-debug/kv_tests

  benchmark:
    name: Performance Benchmark
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Build Dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake

    - name: Configure CMake (Release)
      run: cmake -B build-release -DCMAKE_BUILD_TYPE=Release -S .

    - name: Build Project (Release)
      run: cmake --build build-release

    - name: Run Benchmarks
      run: ./build-release/kv_benchmarks